# DSAssist Agent Configuration

agents:
  planning:
    model: "gpt-4"
    temperature: 0.3
    max_tokens: 1000
    retry_count: 3
    
  codegen:
    model: "gpt-4" 
    temperature: 0.1
    max_tokens: 2000
    retry_count: 3
    
  evaluation:
    model: "gpt-4"
    temperature: 0.2
    max_tokens: 1500
    retry_count: 3

execution:
  timeout: 60  # seconds
  max_memory: 1024  # MB
  work_dir: "./experiments"

llm_routing:
  cost_aware: true
  budget_limit: 100.0  # USD per day
  cheap_models: ["gpt-3.5-turbo"]
  premium_models: ["gpt-4", "claude-3-opus"]
  
experiment:
  max_iterations: 10
  success_threshold: 0.8
  early_stopping: true